tasks:
  - init: sudo apt update
    command: |
        npm i nodemon --global &&
        pyenv install 3.11.1 &&
        pyenv global 3.11.1 &&
        pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.black-formatter
    - ms-pyright.pyright
    - HansUXdev.bootstrap5-snippets